name: Deploy React UI to S3

on:
  push:
    branches:
      - main  # hoặc branch bạn dùng để deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd duy-pha
          npm ci

      - name: Build React app
        run: |
          cd duy-pha
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync duy-pha/build s3://duypha-ui --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1

      - name: (Optional) Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EB62SDR00GXVT --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
